[package]
name = "instant-models"
version = "0.1.0"
edition = "2021"

[dependencies]
postgres-types = { version = "0.2.3", features = ["derive"] }
time = { version = "0.3.9", features = ["parsing"] }
indexmap = { version = "1.8.2" }
thiserror = "1.0.31"
heck = "0.4.0"

[dev-dependencies]
postgres = { version = "0.19.3", features = ["with-chrono-0_4"] }
chrono = "0.4"
